#!/usr/bin/env bash
# INK:rtk-per-project
# RTK per-project hook — installed by Ink Innovation.
# Uses project-local binary: /Users/macbook/Desktop/Desktop - MacBook Pro/INKAviation/ink-agent-dev-helper/.rtk/bin/rtk
# Regenerated by npx ink-agent-dev-helper — do not edit manually.

RTK_BIN="/Users/macbook/Desktop/Desktop - MacBook Pro/INKAviation/ink-agent-dev-helper/.rtk/bin/rtk"

if ! command -v jq &>/dev/null; then
  echo "[rtk] WARNING: jq is not installed." >&2
  exit 0
fi

if [ ! -x "$RTK_BIN" ]; then
  echo "[rtk] WARNING: project-local rtk not found at $RTK_BIN" >&2
  exit 0
fi

INPUT=$(cat)
CMD=$(echo "$INPUT" | jq -r '.tool_input.command // empty')

if [ -z "$CMD" ]; then
  exit 0
fi

# Ink Innovation: smart exclude rules
# Skip RTK only for: already-RTK commands, git diff/show (agents need full patch context),
# ink-tools.js operations, and .planning/ paths.
# git log/status and everything else go through RTK for token savings.

# 1. Already an RTK command — never double-rewrite
case "${CMD%% *}" in
  rtk) exit 0 ;;
esac

# 2. git diff / git show — agents need full patch context for root cause analysis
case "$CMD" in
  "git diff"*|"git show"*) exit 0 ;;
esac

# 2. ink-tools.js operations — deterministic CLI, must not be rewritten
if echo "$CMD" | grep -qF "bin/ink-tools.js"; then
  exit 0
fi

# 3. Commands targeting .planning/ — managed by enforce-ink-tools.js hook
if echo "$CMD" | grep -qF ".planning/"; then
  exit 0
fi

REWRITTEN=$("$RTK_BIN" rewrite "$CMD" 2>/dev/null)
EXIT_CODE=$?

case $EXIT_CODE in
  0)
    [ "$CMD" = "$REWRITTEN" ] && exit 0
    ;;
  1) exit 0 ;;
  2) exit 0 ;;
  3) ;;
  *) exit 0 ;;
esac

ORIGINAL_INPUT=$(echo "$INPUT" | jq -c '.tool_input')
UPDATED_INPUT=$(echo "$ORIGINAL_INPUT" | jq --arg cmd "$REWRITTEN" '.command = $cmd')

if [ "$EXIT_CODE" -eq 3 ]; then
  jq -n --argjson updated "$UPDATED_INPUT" '{"hookSpecificOutput":{"hookEventName":"PreToolUse","updatedInput":$updated}}'
else
  jq -n --argjson updated "$UPDATED_INPUT" '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"allow","permissionDecisionReason":"RTK auto-rewrite","updatedInput":$updated}}'
fi
